# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/olivi/Documents/Universite Laval/Maitrise/DataStreamTest/DataStreamTest.srcs/sources_1/ip/fifo_w16_256_r32_128/fifo_w16_256_r32_128.xci
# IP: The module: 'fifo_w16_256_r32_128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/olivi/Documents/Universite Laval/Maitrise/DataStreamTest/DataStreamTest.gen/sources_1/ip/fifo_w16_256_r32_128/fifo_w16_256_r32_128.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w16_256_r32_128'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/olivi/Documents/Universite Laval/Maitrise/DataStreamTest/DataStreamTest.gen/sources_1/ip/fifo_w16_256_r32_128/fifo_w16_256_r32_128_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w16_256_r32_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/olivi/Documents/Universite Laval/Maitrise/DataStreamTest/DataStreamTest.gen/sources_1/ip/fifo_w16_256_r32_128/fifo_w16_256_r32_128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w16_256_r32_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/olivi/Documents/Universite Laval/Maitrise/DataStreamTest/DataStreamTest.srcs/sources_1/ip/fifo_w16_256_r32_128/fifo_w16_256_r32_128.xci
# IP: The module: 'fifo_w16_256_r32_128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/olivi/Documents/Universite Laval/Maitrise/DataStreamTest/DataStreamTest.gen/sources_1/ip/fifo_w16_256_r32_128/fifo_w16_256_r32_128.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w16_256_r32_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/olivi/Documents/Universite Laval/Maitrise/DataStreamTest/DataStreamTest.gen/sources_1/ip/fifo_w16_256_r32_128/fifo_w16_256_r32_128_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w16_256_r32_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/olivi/Documents/Universite Laval/Maitrise/DataStreamTest/DataStreamTest.gen/sources_1/ip/fifo_w16_256_r32_128/fifo_w16_256_r32_128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w16_256_r32_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
