# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/olivi/Documents/Universite Laval/Maitrise/DataStreamTest/DataStreamTest.srcs/sources_1/ip/fifo_w32_2048_r256_256/fifo_w32_2048_r256_256.xci
# IP: The module: 'fifo_w32_2048_r256_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/olivi/Documents/Universite Laval/Maitrise/DataStreamTest/DataStreamTest.gen/sources_1/ip/fifo_w32_2048_r256_256/fifo_w32_2048_r256_256.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w32_2048_r256_256'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/olivi/Documents/Universite Laval/Maitrise/DataStreamTest/DataStreamTest.gen/sources_1/ip/fifo_w32_2048_r256_256/fifo_w32_2048_r256_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w32_2048_r256_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/olivi/Documents/Universite Laval/Maitrise/DataStreamTest/DataStreamTest.srcs/sources_1/ip/fifo_w32_2048_r256_256/fifo_w32_2048_r256_256.xci
# IP: The module: 'fifo_w32_2048_r256_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/olivi/Documents/Universite Laval/Maitrise/DataStreamTest/DataStreamTest.gen/sources_1/ip/fifo_w32_2048_r256_256/fifo_w32_2048_r256_256.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w32_2048_r256_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/olivi/Documents/Universite Laval/Maitrise/DataStreamTest/DataStreamTest.gen/sources_1/ip/fifo_w32_2048_r256_256/fifo_w32_2048_r256_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_w32_2048_r256_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
